// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/clients/aws.go

// Package mock_clients is a generated GoMock package.
package mock_clients

import (
	s3 "github.com/aws/aws-sdk-go/service/s3"
	gomock "github.com/golang/mock/gomock"
	io "io"
	reflect "reflect"
)

// MockStorageAccessLayer is a mock of StorageAccessLayer interface
type MockStorageAccessLayer struct {
	ctrl     *gomock.Controller
	recorder *MockStorageAccessLayerMockRecorder
}

// MockStorageAccessLayerMockRecorder is the mock recorder for MockStorageAccessLayer
type MockStorageAccessLayerMockRecorder struct {
	mock *MockStorageAccessLayer
}

// NewMockStorageAccessLayer creates a new mock instance
func NewMockStorageAccessLayer(ctrl *gomock.Controller) *MockStorageAccessLayer {
	mock := &MockStorageAccessLayer{ctrl: ctrl}
	mock.recorder = &MockStorageAccessLayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorageAccessLayer) EXPECT() *MockStorageAccessLayerMockRecorder {
	return m.recorder
}

// Upload mocks base method
func (m *MockStorageAccessLayer) Upload(path, filename string, data io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", path, filename, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload
func (mr *MockStorageAccessLayerMockRecorder) Upload(path, filename, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockStorageAccessLayer)(nil).Upload), path, filename, data)
}

// Download mocks base method
func (m *MockStorageAccessLayer) Download(path, filename string, data io.WriterAt) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", path, filename, data)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download
func (mr *MockStorageAccessLayerMockRecorder) Download(path, filename, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockStorageAccessLayer)(nil).Download), path, filename, data)
}

// Read mocks base method
func (m *MockStorageAccessLayer) Read(path, filename string, limit int64, readFrom string) (*s3.ListObjectsV2Output, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", path, filename, limit, readFrom)
	ret0, _ := ret[0].(*s3.ListObjectsV2Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockStorageAccessLayerMockRecorder) Read(path, filename, limit, readFrom interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockStorageAccessLayer)(nil).Read), path, filename, limit, readFrom)
}
