language: go

go:
  - 1.14.x
  - gotip

services:
  - redis-server

env:
  global:
    - REDIS_HOST=localhost
    - REDIS_PORT=6379
    - REDIS_DB=1

install:
  - go get ./...
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace --cover

after_success:
  - bash tools/codecov/format_coverage.sh
  - bash <(curl -s https://codecov.io/bash) || echo "codecov send failed"