// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/client/aws.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/client/aws.go -package mock_clients -destination ./internal/mock/aws_mock.go StorageAccessLayer
//

// Package mock_clients is a generated GoMock package.
package mock_clients

import (
	io "io"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go/service/s3"
	client "github.com/buyco/funicular/pkg/client"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageAccessLayer is a mock of StorageAccessLayer interface.
type MockStorageAccessLayer struct {
	ctrl     *gomock.Controller
	recorder *MockStorageAccessLayerMockRecorder
	isgomock struct{}
}

// MockStorageAccessLayerMockRecorder is the mock recorder for MockStorageAccessLayer.
type MockStorageAccessLayerMockRecorder struct {
	mock *MockStorageAccessLayer
}

// NewMockStorageAccessLayer creates a new mock instance.
func NewMockStorageAccessLayer(ctrl *gomock.Controller) *MockStorageAccessLayer {
	mock := &MockStorageAccessLayer{ctrl: ctrl}
	mock.recorder = &MockStorageAccessLayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageAccessLayer) EXPECT() *MockStorageAccessLayerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStorageAccessLayer) Delete(path string, files ...string) (*s3.DeleteObjectsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range files {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*s3.DeleteObjectsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageAccessLayerMockRecorder) Delete(path any, files ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, files...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorageAccessLayer)(nil).Delete), varargs...)
}

// Download mocks base method.
func (m *MockStorageAccessLayer) Download(path, filename string, data io.WriterAt, options *client.DownloadOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", path, filename, data, options)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockStorageAccessLayerMockRecorder) Download(path, filename, data, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockStorageAccessLayer)(nil).Download), path, filename, data, options)
}

// Read mocks base method.
func (m *MockStorageAccessLayer) Read(path string, limit int64, readFrom string) (*s3.ListObjectsV2Output, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", path, limit, readFrom)
	ret0, _ := ret[0].(*s3.ListObjectsV2Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockStorageAccessLayerMockRecorder) Read(path, limit, readFrom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockStorageAccessLayer)(nil).Read), path, limit, readFrom)
}

// Upload mocks base method.
func (m *MockStorageAccessLayer) Upload(path, filename string, data io.Reader, options *client.UploadOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", path, filename, data, options)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockStorageAccessLayerMockRecorder) Upload(path, filename, data, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockStorageAccessLayer)(nil).Upload), path, filename, data, options)
}
